In [1]:
from scipy.io import loadmat as lm
import statsmodels.formula.api as sf
import statsmodels.api as sm
from pandas import DataFrame as df
from pandas import read_csv
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
subs = ['Sub01', 'Sub02', 'Sub04', 'Sub05', 'Sub06', 'Sub08', 'Sub10', 'Sub11', 'Sub13']
nSub = len(subs)

In [3]:
# Load the best x values for each subject
#subXs_allCD = np.array(read_csv('SubXs_all.csv', header=None))
subXs_allCD_posParam = np.array(read_csv('SubXs_all_posParam.csv', header=None))
#subXs_no0CD = np.array(read_csv('SubXs_noZeroCD.csv', header=None))
#subXs_no0CD_posParam = np.array(read_csv('SubXs_noZeroCD_posParam.csv', header=None))

In [ ]:
# Create regressors for distance and coherence for each subject.
# To do this, first get the values from the DirCoh<sub>.mat files.

dreg1 = np.zeros((20,nSub))
creg1 = np.zeros((20,nSub))
params1 = np.zeros((3,nSub))
pvals1 = np.zeros((3,nSub))
gof1  = np.zeros((2,nSub))

for si in range(nSub):
    cdmat = lm('..\\Data\\Behavior\\DirCoh' + subs[si] + '.mat')
    # In the DirCoh matrix, the first column is distance and second is coherence
    dist = np.unique(np.abs(cdmat['DirCoh'][:,0]))
    coh = np.unique(cdmat['DirCoh'][:,1])
    # In the x arrays, distance goes through all values before coherence changes
    temp = np.ones((4,5)) * dist[0:5]/dist[4]
    dreg1[:,si] = temp.flatten()
    temp = np.ones((5,4)) * coh
    creg1[:,si] = temp.T.flatten()
    
    data = df({'coh' : creg1[:,si],
               'dist' : dreg1[:,si],
               'x' : subXs_allCD[:,si]})
    
    est = sf.ols(formula = 'x ~ coh * dist', data = data).fit()
    
    # Save the values of betas and their p-values
    params1[0,si] = est.params['coh']
    params1[1,si] = est.params['dist']
    params1[2,si] = est.params['coh:dist']
    
    pvals1[0,si] = est.pvalues['coh']
    pvals1[1,si] = est.pvalues['dist']
    pvals1[2,si] = est.pvalues['coh:dist']
    
    gof1[0,si] = est.rsquared
    gof1[1,si] = est.fvalue

In [ ]:
import matplotlib.lines as ln

In [ ]:
Y = subXs_allCD[:,0]
X1 = creg1[:,0]
X2 = dreg1[:,0]
plt.plot(X1, Y, '.b')
plt.plot(X2, Y, '.r')
plt.plot(est.params['Intercept']+X1*est.params['coh']+X2*est.params['dist']+X1*X2*est.params[3], 'b.-')

plt.axis([-0.5, 1.5, -0.5, 2.5])
ln.Line2D(xdata = est.params['Intercept']+Y*est.params['coh'], ydata = Y, color = 'b')
ln.Line2D(xdata = est.params['Intercept']+Y*est.params['dist'], ydata = Y, color = 'r')

In [4]:
# Create regressors for distance and coherence for each subject.
# To do this, first get the values from the DirCoh<sub>.mat files.

dreg5 = np.zeros((20,nSub))
creg5 = np.zeros((20,nSub))
params5 = np.zeros((3,nSub))
pvals5 = np.zeros((3,nSub))
gof5 = np.zeros((2,nSub))

for si in range(nSub):
    cdmat = lm('..\\Data\\Behavior\\DirCoh' + subs[si] + '.mat')
    # In the DirCoh matrix, the first column is distance and second is coherence
    dist = np.unique(np.abs(cdmat['DirCoh'][:,0]))
    coh = np.unique(cdmat['DirCoh'][:,1])
    # In the x arrays, distance goes through all values before coherence changes
    temp = np.ones((4,5)) * dist[0:5]/dist[4]
    dreg5[:,si] = temp.flatten()
    temp = np.ones((5,4)) * coh
    creg5[:,si] = temp.T.flatten()
    
    data = df({'coh' : creg5[:,si],
               'dist' : dreg5[:,si],
               'x' : subXs_allCD_posParam[:,si]})
    
    est = sf.ols(formula = 'x ~ coh * dist', data = data).fit()
    
    # Save the values of betas and their p-values
    params5[0,si] = est.params['coh']
    params5[1,si] = est.params['dist']
    params5[2,si] = est.params['coh:dist']
    
    pvals5[0,si] = est.pvalues['coh']
    pvals5[1,si] = est.pvalues['dist']
    pvals5[2,si] = est.pvalues['coh:dist']
    
    gof5[0,si] = est.rsquared
    gof5[1,si] = est.fvalue

In [ ]:
# Create regressors for distance and coherence for each subject.
# To do this, first get the values from the DirCoh<sub>.mat files.

dreg2 = np.zeros((12,nSub))
creg2 = np.zeros((12,nSub))
params2 = np.zeros((3,nSub))
pvals2 = np.zeros((3,nSub))
gof2 = np.zeros((2,nSub))

for si in range(nSub):
    cdmat = lm('..\\Data\\Behavior\\DirCoh' + subs[si] + '.mat')
    # In the DirCoh matrix, the first column is distance and second is coherence
    dist = np.unique(np.abs(cdmat['DirCoh'][:,0]))
    coh = np.unique(cdmat['DirCoh'][:,1])
    # In the x arrays, distance goes through all values before coherence changes
    temp = np.ones((3,4)) * dist[1:5]/dist[4]
    dreg2[:,si] = temp.flatten()
    temp = np.ones((4,3)) * coh[1:]
    creg2[:,si] = temp.T.flatten()
    
    data = df({'coh' : creg2[:,si],
               'dist' : dreg2[:,si],
               'x' : subXs_no0CD[:,si]})
    
    est = sf.ols(formula = 'x ~ coh * dist', data = data).fit()
    
    # Save the values of betas and their p-values
    params2[0,si] = est.params['coh']
    params2[1,si] = est.params['dist']
    params2[2,si] = est.params['coh:dist']
    
    pvals2[0,si] = est.pvalues['coh']
    pvals2[1,si] = est.pvalues['dist']
    pvals2[2,si] = est.pvalues['coh:dist']
    
    gof2[0,si] = est.rsquared
    gof2[1,si] = est.fvalue

In [ ]:
# Create regressors for distance and coherence for each subject.
# To do this, first get the values from the DirCoh<sub>.mat files.

dreg3 = np.zeros((12,nSub))
creg3 = np.zeros((12,nSub))
params3 = np.zeros((3,nSub))
pvals3 = np.zeros((3,nSub))
gof3 = np.zeros((2,nSub))

for si in range(nSub):
    cdmat = lm('..\\Data\\Behavior\\DirCoh' + subs[si] + '.mat')
    # In the DirCoh matrix, the first column is distance and second is coherence
    dist = np.unique(np.abs(cdmat['DirCoh'][:,0]))[1:5]
    coh = np.unique(cdmat['DirCoh'][:,1])[1:]
    # In the x arrays, distance goes through all values before coherence changes
    temp = np.ones((3,4)) * (dist - dist[0])
    temp /= dist[-1]
    dreg3[:,si] = temp.flatten()
    temp = np.ones((4,3)) * (coh - coh[0])
    temp /= coh[-1]
    creg3[:,si] = temp.T.flatten()
    
    data = df({'coh' : creg3[:,si],
               'dist' : dreg3[:,si],
               'x' : subXs_no0CD[:,si]})
    
    est = sf.ols(formula = 'x ~ coh * dist', data = data).fit()
    
    # Save the values of betas and their p-values
    params3[0,si] = est.params['coh']
    params3[1,si] = est.params['dist']
    params3[2,si] = est.params['coh:dist']
    
    pvals3[0,si] = est.pvalues['coh']
    pvals3[1,si] = est.pvalues['dist']
    pvals3[2,si] = est.pvalues['coh:dist']
    
    gof3[0,si] = est.rsquared
    gof3[1,si] = est.fvalue

In [ ]:
# Create regressors for distance and coherence for each subject.
# To do this, first get the values from the DirCoh<sub>.mat files.

dreg4 = np.zeros((12,nSub))
creg4 = np.zeros((12,nSub))
params4 = np.zeros((3,nSub))
pvals4 = np.zeros((3,nSub))
gof4 = np.zeros((2,nSub))

for si in range(nSub):
    cdmat = lm('..\\Data\\Behavior\\DirCoh' + subs[si] + '.mat')
    # In the DirCoh matrix, the first column is distance and second is coherence
    dist = np.unique(np.abs(cdmat['DirCoh'][:,0]))
    coh = np.unique(cdmat['DirCoh'][:,1])
    # In the x arrays, distance goes through all values before coherence changes
    temp = np.ones((3,4)) * dist[1:5]/dist[4]
    dreg4[:,si] = temp.flatten()
    temp = np.ones((4,3)) * coh[1:]
    creg4[:,si] = temp.T.flatten()
    
    data = df({'coh' : creg4[:,si],
               'dist' : dreg4[:,si],
               'x' : subXs_no0CD_posParam[:,si]})
    
    est = sf.ols(formula = 'x ~ coh * dist', data = data).fit()
    
    # Save the values of betas and their p-values
    params4[0,si] = est.params['coh']
    params4[1,si] = est.params['dist']
    params4[2,si] = est.params['coh:dist']
    
    pvals4[0,si] = est.pvalues['coh']
    pvals4[1,si] = est.pvalues['dist']
    pvals4[2,si] = est.pvalues['coh:dist']
    
    gof4[0,si] = est.rsquared
    gof4[1,si] = est.fvalue

In [ ]:
# Plot the X-Y relationships in each of the cases
ctr = 1
for si in range(9):
    plt.figure()
    plt.subplot(1, 4, ctr)
    #plt.plot(creg1[:,si], subXs_allCD[:,si], 'r.')
    plt.plot(dreg1[:,si], subXs_allCD[:,si], 'b.')
    plt.axis('equal')
    ctr += 1
    
    plt.subplot(1, 4, ctr)
    #plt.plot(creg2[:,si], subXs_no0CD[:,si], 'r.')
    plt.plot(dreg2[:,si], subXs_no0CD[:,si], 'b.')
    plt.axis('equal')
    ctr += 1
    
    plt.subplot(1, 4, ctr)
    #plt.plot(creg3[:,si], subXs_no0CD[:,si], 'r.')
    plt.plot(dreg3[:,si], subXs_no0CD[:,si], 'b.')
    plt.axis('equal')
    ctr += 1
    
    plt.subplot(1, 4, ctr)
    
    #plt.plot(creg4[:,si], subXs_no0CD_posParam[:,si], 'r.')
    plt.plot(dreg4[:,si], subXs_no0CD_posParam[:,si], 'b.')
    plt.axis('equal')
    ctr = 1
    

In [ ]:
print(stats.kstest(np.array([0, 0.12, 0.25, 1]), 'norm'))
print(stats.kstest(np.array([0, 0.12, 0.25, 1]) - np.mean(np.array([0, 0.12, 0.25, 1])), 'norm'))
print(stats.kstest(np.array([0, 12, 25, 100]), 'norm'))
print(stats.kstest(np.array([0, 15, 45, 75, 90])/90, 'norm'))
print(stats.kstest(np.array([0, 15, 45, 75, 90])/90 - np.mean(np.array([0, 15, 45, 75, 90])/90), 'norm'))
print(stats.kstest(np.array([0, 15, 45, 75, 90]), 'norm'))
print(stats.kstest(np.array([-0.3439, -0.2957, -0.2232, 0.8628]), 'norm'))
print(stats.kstest(subXs_allCD[:,0], 'norm'))
print(stats.kstest(subXs_allCD[:,0] / np.std(subXs_allCD[:,0]), 'norm'))

In [ ]:
rhead = ['Coh:', 'Dist:', 'Ixn:']

for si in range(nSub):
    print(subs[si])
    for ci in range(3):
        print(rhead[ci], round(params1[ci,si],ndigits=2), '|', round(pvals1[ci,si],ndigits=2), '|||', 
             round(params5[ci,si],ndigits=2), '|', round(pvals5[ci,si],ndigits=2), '|||', 
             round(params2[ci,si],ndigits=2), '|', round(pvals2[ci,si],ndigits=2), '|||',
             round(params3[ci,si],ndigits=2), '|', round(pvals3[ci,si],ndigits=2), '|||',
             round(params4[ci,si],ndigits=2), '|', round(pvals4[ci,si],ndigits=2))
    print

In [ ]:
subXs_allCD[:,5].reshape((4,5))

In [8]:
[subXs_allCD_posParam.round(decimals=2), creg5.round(decimals=2), dreg5.round(decimals=2)]

[array([[ 0.09,  0.06,  0.19,  0.21,  0.11,  0.26,  0.19,  0.16,  0.19],
        [ 0.06,  0.04,  0.24,  0.24,  0.11,  0.31,  0.16,  0.14,  0.11],
        [ 0.11,  0.06,  0.14,  0.16,  0.14,  0.09,  0.14,  0.09,  0.26],
        [ 0.06,  0.06,  0.09,  0.11,  0.09,  0.09,  0.19,  0.11,  0.14],
        [ 0.09,  0.06,  0.09,  0.34,  0.24,  0.19,  0.09,  0.19,  0.19],
        [ 0.14,  0.04,  0.19,  0.11,  0.21,  0.39,  0.19,  0.19,  0.09],
        [ 0.11,  0.11,  0.14,  0.19,  0.44,  0.44,  0.36,  0.44,  0.24],
        [ 0.31,  0.41,  0.96,  0.64,  0.94,  0.64,  0.81,  0.84,  0.21],
        [ 0.29,  0.41,  0.99,  0.76,  1.06,  0.71,  1.04,  1.04,  0.34],
        [ 0.61,  0.36,  0.91,  0.76,  1.04,  0.74,  1.04,  0.99,  0.21],
        [ 0.06,  0.06,  0.11,  0.21,  0.11,  0.16,  0.16,  0.21,  0.19],
        [ 0.44,  0.16,  0.39,  0.56,  0.76,  0.39,  0.46,  0.39,  0.26],
        [ 0.84,  0.64,  1.64,  1.41,  1.59,  0.84,  1.46,  1.51,  0.31],
        [ 0.94,  0.66,  2.09,  1.34,  1.49,  0.91, 

In [ ]:
print(df([gof1[0,:], gof5[0,:], gof2[0,:], gof4[0,:]]))
print(df([gof1[1,:], gof5[1,:], gof2[1,:], gof4[1,:]]))

In [13]:
pvals5[0,:].round(decimals=2)

array([ 0.43,  0.08,  0.99,  0.57,  0.28,  0.81,  0.74,  0.96,  0.13])

In [14]:
pvals5[1,:].round(decimals=2)

array([ 0.24,  0.06,  0.21,  0.11,  0.13,  0.56,  0.09,  0.09,  0.26])

In [18]:
pvals5[2,:]

array([  2.99799331e-05,   5.79587100e-11,   2.96353839e-04,
         1.10512681e-03,   3.89761911e-03,   8.53447747e-06,
         1.50078396e-03,   2.51730987e-02,   1.82683584e-04])

In [20]:
gof5[0,:].round(decimals=2)

array([ 0.89,  0.98,  0.85,  0.84,  0.83,  0.91,  0.83,  0.71,  0.89])

In [21]:
np.mean(gof5[0,:])

0.85786990776496264

In [24]:
np.max(subXs_allCD_posParam,0)

array([ 2.89,  5.  ,  3.27,  2.34,  2.79,  1.97,  2.49,  1.97,  2.14])